# A workflow to run against renovate-bot's PRs,
# such as `npm run bundle` after it updates the package.json and
# package-lock.json files.

# The potentially untrusted code is first run inside a low-privilege Job, and
# the diff is uploaded as an artifact. Then a higher-privilege Job applies the
# diff and pushes the changes to the PR. It's important to only run this
# workflow against PRs from trusted sources, after also reviewing the changes!

# There have been vulnerabilities with using `git apply`
# https://github.blog/2023-04-25-git-security-vulnerabilities-announced-4/
#
# At this point a compromised git binary cannot modify any of this repo's
# branches, only the PR fork's branch, due to our branch protection rules and
# CODEOWNERS. It aslso cannot submit a new release or modify exsiting releases
# due to tag protection rules.

name: Update Actions dist/ post-commit
run-name: "Updating dist/ for PR #${{ inputs.pr_number }}"

on:
  workflow_dispatch:
    inputs:
      pr_number:
        type: number
        description: Pull Request number
        required: true

# Grant no permissions by default
permissions: {}

jobs:
  check:
    name: Check action changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: actions/installer
    outputs:
      has-change: ${{ steps.compare.outputs.diff }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
          sparse-checkout: |
            actions/installer/

      - name: Checkout PR
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ inputs.pr_number }}
        run: gh pr checkout "$PR_NUMBER"

      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: actions/installer/.node-version
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Check Format
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run ci-test

      - name: Build dist/ Directory
        run: npm run package

      - name: Compare Directories
        id: compare
        shell: bash
        run: |
          if [ ! -d dist/ ]; then
            echo "::error::Expected dist/ directory does not exist"
            exit 1
          fi

          [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -eq 0 ] && DIFF=false || DIFF=true
          echo "diff=$DIFF" | tee -a "$GITHUB_OUTPUT"
          if [ "$DIFF" == "true" ]; then
            echo "::warning::Detected uncommitted changes after build"
          fi

      - name: Upload dist/
        if: (!cancelled()) && steps.compare.outputs.diff == 'true'
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: dist
          path: actions/installer/dist

  push:
    name: Apply & Push changes
    if: needs.check.outputs.has-change == 'true'
    needs: [check]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: write
    defaults:
      run:
        working-directory: actions/installer
    steps:
      - name: Checkout repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          sparse-checkout: |
            actions/installer/

      - name: Checkout PR
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ inputs.pr_number }}
        run: gh pr checkout "$PR_NUMBER"

      - name: Download diff
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: dist
          path: actions/installer/dist

      - name: Push changes back into PR
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git status
          git commit -s -m "chore: Updating installer action dist/"
          git push
